HOST = "0.0.0.0"
PORT = 12345
BUFFER_SIZE = 2048


CLIENTS_SET_PREFIX = b"####CLIENTS_SET_PREFIX#"
ENCRYPTED_SETS_PREFIX = b"#ENCRYPTED_SETS_PREFIX#"

assert len(CLIENTS_SET_PREFIX) == len(ENCRYPTED_SETS_PREFIX)
PREFIX_FIXED_SIZE = len(CLIENTS_SET_PREFIX)
