import os

PAGE_SIZE = os.sysconf("SC_PAGE_SIZE") // 16
NUMBER_OF_PAGES = 20


HOST = "0.0.0.0"
PORT = 12345

CHALLANGE_PREFIX = b"PREFIX_C#"
FILE_PREFIX = b"PREFIX_F#"

assert len(CHALLANGE_PREFIX) == len(FILE_PREFIX)
PREFIX_FIXED_SIZE = len(CHALLANGE_PREFIX)
